{"name":"User repository find by credentials failure","fullName":"TestUserFindByCredentialsSuite/User repository find by credentials/TestFindByCredentials_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727876946212,"stop":1727876946212,"uuid":"177360ba-80c5-11ef-9769-ca15b1947337","historyId":"3181338ec94c59938b695cc347d036dc","testCaseId":"042068ed992bf987983782be9259c7d7","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestUserFindByCredentialsSuite/User repository find by credentials/TestFindByCredentials_Failure"},{"name":"suite","value":"User repository find by credentials"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727876946212,"stop":1727876946212,"parameters":[{"name":"Error","value":"sql: no rows in result set: record does not exist"},{"name":"Target","value":"record does not exist"}]}]}