{"name":"User repository delete user failure","fullName":"TestUserDeleteSuite/User repository delete user/TestDelete_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727876946214,"stop":1727876946214,"uuid":"1773baa6-80c5-11ef-9769-ca15b1947337","historyId":"4201b5fc9741fdf709d48a149e1a9a18","testCaseId":"e040cff821fa62de9a437fddeae7b54b","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestUserDeleteSuite/User repository delete user/TestDelete_Failure"},{"name":"suite","value":"User repository delete user"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727876946214,"stop":1727876946214,"parameters":[{"name":"Error","value":"sql: connection is already closed: record delete failed"},{"name":"Target","value":"record delete failed"}]}]}