{"name":"Review repository create review failure","fullName":"TestReviewCreateSuite/Review repository create review/TestCreate_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727875153117,"stop":1727875153117,"uuid":"eaaec0e6-80c0-11ef-9e41-ca15b1947337","historyId":"b211308ac5d19f5cc2e396178e46cf72","testCaseId":"eab8ab0ab7a855ff6261d32c844730fd","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestReviewCreateSuite/Review repository create review/TestCreate_Failure"},{"name":"suite","value":"Review repository create review"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727875153117,"stop":1727875153117,"parameters":[{"name":"Error","value":"sql: connection is already closed: persistence internal error"},{"name":"Target","value":"persistence internal error"}]}]}