{"name":"User repository create user failure","fullName":"TestUserCreateSuite/User repository create user/TestCreate_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727875153125,"stop":1727875153125,"uuid":"eaaff3ee-80c0-11ef-9e41-ca15b1947337","historyId":"b12e99bd9073cab1b6157c8c7ef64162","testCaseId":"8022ce96e13dd915a95763b7aa58e98c","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"macbook.local"},{"name":"thread","value":"TestUserCreateSuite/User repository create user/TestCreate_Failure"},{"name":"suite","value":"User repository create user"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727875153125,"stop":1727875153125,"parameters":[{"name":"Error","value":"sql: connection is already closed: persistence internal error"},{"name":"Target","value":"persistence internal error"}]}]}