{"name":"User repository find by credentials failure","fullName":"TestUserFindByCredentialsSuite/User repository find by credentials/TestFindByCredentials_Failure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727773563260,"stop":1727773563260,"uuid":"6268d52e-7fd4-11ef-a987-ca15b1947338","historyId":"3181338ec94c59938b695cc347d036dc","testCaseId":"042068ed992bf987983782be9259c7d7","labels":[{"name":"language","value":"go1.22.5"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"h19.net58.bmstu.ru"},{"name":"thread","value":"TestUserFindByCredentialsSuite/User repository find by credentials/TestFindByCredentials_Failure"},{"name":"suite","value":"User repository find by credentials"},{"name":"package","value":"github.com/paw1a/eschool/internal/adapter/repository/postgres/test"}],"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727773563260,"stop":1727773563260,"parameters":[{"name":"Error","value":"sql: no rows in result set: record does not exist"},{"name":"Target","value":"record does not exist"}]}]}